import Head from "next/head";

import Layout from "../components/Layout";
import Hero from "../components/Hero";
import Services from "../components/Services";
import DeliveryInfo from "../components/DeliveryInfo";
import classes from '../styles/home.module.css';
import { useState } from "react";
import toast, { Toaster } from "react-hot-toast";

export default function Home() {

  return (
    <Layout>
      <div className={classes.container}>
        <Head>
          <title>Taufers Express</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png"></link>
          <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
          <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
          <link rel="manifest" href="/site.webmanifest"></link>
        </Head>
        <main>
          <Hero />
          <Services />
          <DeliveryInfo />
        </main>
      </div>
      <Toaster />
    </Layout>
  );
}


